In [70]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [45]:
list_1=[1,2,3,4]

In [11]:
a=np.array(list_1)

In [13]:
a

array([1, 2, 3, 4])

In [14]:
b=np.array([[1,2,3],[4,5,6]])

In [15]:
print(b.shape)

(2, 3)


In [44]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
lst = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [21]:
arr = np.array(lst)

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a = arr[1:,1:]
print(a)

[[5 6]
 [8 9]]


In [24]:
a = arr[0:2, 0:2]
print(a)

[[1 2]
 [4 5]]


In [25]:
a = arr[1:,1:]
print(a)

[[5 6]
 [8 9]]


In [29]:
bool_array = np.array([
    [False, True, False],
    [True, False, True],
    [False, True, False]
])

In [36]:
n = arr[bool_array];
print(n)

[2 4 6 8]


In [30]:
a= np.array(lst)
bool_indexing = (a % 2 ==0)
print(bool_indexing)
print(a[bool_indexing])

[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


In [32]:
print(a[bool_indexing])
n = a[ a % 2 == 0 ]

[2 4 6 8]


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [59]:
a=np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [60]:
b=np.arange(4,8).reshape(2,2)
b

array([[4, 5],
       [6, 7]])

In [62]:
c= a+b
c= np.add(a,b)
print(c)

[[ 4  6]
 [ 8 10]]


In [69]:
c = b - a
c = np.subtract(b , a)
print(c)

[[4 4]
 [4 4]]


In [65]:
c = a * b
c = np.multiply(a,b)
print(c)

[[ 0  5]
 [12 21]]


In [66]:
c = a / b
c = np.divide(a,b)
print(c)

[[0.         0.2       ]
 [0.33333333 0.42857143]]


In [71]:
ar1=np.arange(4)

In [72]:
ar1

array([0, 1, 2, 3])

In [73]:
ar1=np.arange(4).reshape(2,2)

In [74]:
ar1

array([[0, 1],
       [2, 3]])

In [81]:
np.concatenate([ar1,ar1],axis=0)

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [82]:
np.concatenate([ar1,ar1],axis=1)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [83]:
df1=DataFrame({'a':[1,2,3],'b':[4,5,6]})
df1

a  b
0  1  4
1  2  5
2  3  6

In [84]:
df2=DataFrame({'a':[10,11],'b':[40,50]})
df2

a   b
0  10  40
1  11  50

In [86]:
df3=DataFrame({'a':[40,50,60],'b':[70,80,90],'c':[10,11,12]})
df3

a   b   c
0  40  70  10
1  50  80  11
2  60  90  12

In [87]:
pd.concat([df1,df2])

a   b
0   1   4
1   2   5
2   3   6
0  10  40
1  11  50

In [88]:
pd.concat([df1,df2],axis=1)

a  b     a     b
0  1  4  10.0  40.0
1  2  5  11.0  50.0
2  3  6   NaN   NaN

In [94]:
a=pd.concat([df1,df2],axis=1,join='inner',keys=['one','two'])

In [95]:
a

one    two    
    a  b   a   b
0   1  4  10  40
1   2  5  11  50

In [100]:
b=pd.concat([df1,df2],axis=0,join='inner',keys=['one','two'])

In [101]:
b

a   b
one 0   1   4
    1   2   5
    2   3   6
two 0  10  40
    1  11  50

In [104]:
df1=DataFrame({'A':[1,2,3,4],'B':[5,6,7,8],'C':[9,10,11,12]})

In [105]:
df1

A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [109]:
df2=DataFrame({'A':['a','b','c','d'],'D':['e','f','g','h'],'E':['i','j','k','l']})

In [110]:
df2

A  D  E
0  a  e  i
1  b  f  j
2  c  g  k
3  d  h  l

In [111]:
df1.combine_first(df2)

A  B   C  D  E
0  1  5   9  e  i
1  2  6  10  f  j
2  3  7  11  g  k
3  4  8  12  h  l